<#
.SYNOPSIS
Installs PSAppDeployToolkit and shows a reboot prompt to the user.

.DESCRIPTION
Ensures NuGet provider and PSGallery trust are configured, installs and imports the
PSAppDeployToolkit module, then displays a restart prompt using
Show-ADTInstallationRestartPrompt. The last 5 minutes of the countdown are displayed 
to the user, and the restart is forced after. A tag file is used to prevent the script from
prompting again on subsequent runs (reboot loop protection). All actions are logged
to a transcript file in the user profile, which is hidden once writing completes.

.PARAMETER CountdownMinutes
Number of minutes before the restart prompt forces a reboot. This value is converted
to seconds for CountdownSeconds. Default is 30 minutes.

.NOTES

.AUTHOR
Kasper M. Johansen | kasperjohansen.net
#>

#Requires -Version 5.1

[CmdletBinding(SupportsShouldProcess)]
param(
    # Minutes until forced restart, converted to seconds for the prompt
    [Parameter()]
    [int]$CountdownMinutes = 30
)

$ErrorActionPreference = 'Stop'

# Convert minutes to seconds for the countdown
$CountdownSeconds = $CountdownMinutes * 60

# Logging setup
$LogFile = "Scheduled_Reboot_$(Get-Date -Format 'yyyyMMdd_HHmmss').txt"

# Start logging
Start-Transcript -Path $(Join-Path "$env:USERPROFILE" "$LogFile") -NoClobber
If (!(Test-Path -Path "$env:USERPROFILE\Scheduled_Reboot_tag.tag"))
{
# Create tag file to prevent reboot loop
Write-Output "Creating tag file to prevent reboot loop"
Set-Content -Path "$env:USERPROFILE\Scheduled_Reboot_tag.tag" -Value "Restartet" -Force
Set-ItemProperty -Path "$env:USERPROFILE\Scheduled_Reboot_tag.tag" -Name Attributes -Value ([System.IO.FileAttributes]::Hidden)

# Install NuGet provider if not already installed
if (-not (Get-PackageProvider -Name NuGet -ListAvailable -ErrorAction SilentlyContinue)) 
{
    Write-Output "NuGet provider not found. Installing NuGet provider..."
    Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force -Scope CurrentUser -ErrorAction Stop | Out-Null
}

# Set PSGallery repository to Trusted if it is not already set
$psg = Get-PSRepository -Name "PSGallery" -ErrorAction SilentlyContinue
if ($psg -and $psg.InstallationPolicy -ne "Trusted") 
{
    Write-Output "Setting PSGallery repository to Trusted..."
    Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted -ErrorAction SilentlyContinue
}

# Install PSAppDeployToolkit module if not already installed
Write-Output "Installing PSAppDeployToolkit module..."
Install-Module -Name PSAppDeployToolkit -Scope CurrentUser -Force -AllowClobber

Write-Output "Importing PSAppDeployToolkit module..."
Import-Module -Name PSAppDeployToolkit

# Show a reboot prompt to the user
Write-Output "PSADT installation complete. Setting up reboot prompt..."
Show-ADTInstallationRestartPrompt -Title 'Reboot required' -Subtitle "Your computer will restart in $CountdownMinutes minutes to ensure it meets our IT security requirements. Thank you for your understanding." -CountdownSeconds $CountdownSeconds -CountdownNoHideSeconds 300 -AllowMove -NotTopMost

}
else
{
    Write-Output "Scheduled reboot has already happened. Exiting."
}
Stop-Transcript

# Sleep for 30 seconds to ensure the log file is written before hiding it
Start-Sleep -Seconds 30
Set-ItemProperty -Path $(Join-Path "$env:USERPROFILE" "$LogFile") -Name Attributes -Value ([System.IO.FileAttributes]::Hidden)
# SIG # Begin signature block
# MIIeegYJKoZIhvcNAQcCoIIeazCCHmcCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCBnEt9EiIBHL8pO
# mOVP3kn/GRT1oxOZDgdSFP0QxPFbfaCCA9YwggPSMIICuqADAgECAgg7LtLmDulW
# 1TANBgkqhkiG9w0BAQ0FADCBizELMAkGA1UEBhMCREsxEzARBgNVBAcTCkNvcGVu
# aGFnZW4xIDAeBgkqhkiG9w0BCQEWEWluZm9Acm9ib3BhY2suY29tMREwDwYDVQQK
# EwhSb2JvcGFjazEyMDAGA1UEAxMpS2FzcGVyIFN2ZW4gTW96YXJ0IEpvaGFuc2Vu
# IChQcml2YXRlIGxhYikwHhcNMjUwMzI3MDcxMTMxWhcNNDUwMzI3MDcxMTMxWjCB
# izELMAkGA1UEBhMCREsxEzARBgNVBAcTCkNvcGVuaGFnZW4xIDAeBgkqhkiG9w0B
# CQEWEWluZm9Acm9ib3BhY2suY29tMREwDwYDVQQKEwhSb2JvcGFjazEyMDAGA1UE
# AxMpS2FzcGVyIFN2ZW4gTW96YXJ0IEpvaGFuc2VuIChQcml2YXRlIGxhYikwggEi
# MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQChmJK3YhB0e9BrQ1QVXlUkhfyX
# JYN4TCwugk6ZvZP0Q7Qoyctax/NGZCQrt8GNKqVR1dMycEvXjfgsY7qPgtjE4yTd
# RabcswZK0GiaOsk0GO5PM8jdOKP/w3+7gc7Ev8kU9pMPM11QgQVE/JAa6T0as/y6
# nbIyeNCqfPseC4Rx0r17mjJkRHkUJOUBY4uuXzxLTiwqolJmJstDt2/dfhTx2wKm
# +iDzyi9+th3HoMteB13QIPc6uhc4mXJkVleDeKouRt2xpIPOZUY0ZakKochP6ghr
# h/J7pJHk/zwcEegogBApFVFfkh+d5nkDLOvefLN2UCLDpvXU7Nw6LE/z2BmFAgMB
# AAGjODA2MA4GA1UdDwEB/wQEAwIHgDAPBgNVHRMBAf8EBTADAgEBMBMGA1UdJQQM
# MAoGCCsGAQUFBwMDMA0GCSqGSIb3DQEBDQUAA4IBAQBeSoJ0PYSR1xH+8ws8PP4F
# mhVrfT7k7o4hAANZGR+HYxr+0yKPTkBtHC3G2vIbsVcnBKtNiTb519LQDPTssjmw
# xji9F9l2gG6kS0axaQyRfIDpEdswcrCCo+YIh6Suc8GZsc2nxBzSRpdMzA0bAq8A
# FUd9GyotByr8OHWh5Toxhw/lCwQOtBfPGA5deHMSRNXAOihXeatsz4ufk5LVX/lL
# oDsr2lvdsh+N2JBHn/0ElFp83qaqKbroCKlrpYPwrh+OfP6VQiku5Wzz+2VlGhsV
# Lsrhp//CAenx2ki+GcQcz72CfLCWt0f28swM90KSzXgi7nCpESpuOF8654aktbaz
# MYIZ+jCCGfYCAQEwgZgwgYsxCzAJBgNVBAYTAkRLMRMwEQYDVQQHEwpDb3Blbmhh
# Z2VuMSAwHgYJKoZIhvcNAQkBFhFpbmZvQHJvYm9wYWNrLmNvbTERMA8GA1UEChMI
# Um9ib3BhY2sxMjAwBgNVBAMTKUthc3BlciBTdmVuIE1vemFydCBKb2hhbnNlbiAo
# UHJpdmF0ZSBsYWIpAgg7LtLmDulW1TANBglghkgBZQMEAgEFAKCBuDAZBgkqhkiG
# 9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIB
# FTAvBgkqhkiG9w0BCQQxIgQg7AR5Lc3uWVVb/knulZCEJW4FgmP6xksGi+8NMEpY
# Ps0wTAYKKwYBBAGCNwIBDDE+MDygIoAgAFIAbwBiAG8AcABhAGMAawAgAHAAYQBj
# AGsAYQBnAGWhFoAUaHR0cHM6Ly9yb2JvcGFjay5jb20wDQYJKoZIhvcNAQEBBQAE
# ggEAPEcDXTcFmzLn7APxVzLThG+KFdMxXAsIFuJncwWc5CV2s0hA2rYGzbQj+KJ3
# wYV26I/rhiycYbsXksixLrCpckLd053Cg0u3XSoE7JgnKbg8qpDn4OTQY738KT0K
# dycWnfXrYK0+thmOFz8xFyuDKL+cpLaAXP1t8caIXH3aK4dPU3WiEHPYhq1HG3To
# Xx2qj4WMO6KasaUaTx/sgYVJ1bCW9RSjmqukWHlPh2t8sRw9gatRvADK57g711rL
# zvEagm+03YjX+9HPxjSuOAnaskYtBwv/HjwroQALLXUS+sXuDFOxIgz5iY/WkwVa
# 8DvcEmnmYK7kr8We5orJQWQgIKGCF3cwghdzBgorBgEEAYI3AwMBMYIXYzCCF18G
# CSqGSIb3DQEHAqCCF1AwghdMAgEDMQ8wDQYJYIZIAWUDBAIBBQAweAYLKoZIhvcN
# AQkQAQSgaQRnMGUCAQEGCWCGSAGG/WwHATAxMA0GCWCGSAFlAwQCAQUABCBe2BcL
# nlpdsOR3uiWP5QUniqZ08XQ95uBYjVKQTX1jBwIRAMXk/apDHyjkq+qZXbQ5ZA0Y
# DzIwMjYwNzAyMTMxODQ3WqCCEzowggbtMIIE1aADAgECAhAKgO8YS43xBYLRxHan
# lXRoMA0GCSqGSIb3DQEBCwUAMGkxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdp
# Q2VydCwgSW5jLjFBMD8GA1UEAxM4RGlnaUNlcnQgVHJ1c3RlZCBHNCBUaW1lU3Rh
# bXBpbmcgUlNBNDA5NiBTSEEyNTYgMjAyNSBDQTEwHhcNMjUwNjA0MDAwMDAwWhcN
# MzYwOTAzMjM1OTU5WjBjMQswCQYDVQQGEwJVUzEXMBUGA1UEChMORGlnaUNlcnQs
# IEluYy4xOzA5BgNVBAMTMkRpZ2lDZXJ0IFNIQTI1NiBSU0E0MDk2IFRpbWVzdGFt
# cCBSZXNwb25kZXIgMjAyNSAxMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
# AgEA0EasLRLGntDqrmBWsytXum9R/4ZwCgHfyjfMGUIwYzKomd8U1nH7C8Dr0cVM
# F3BsfAFI54um8+dnxk36+jx0Tb+k+87H9WPxNyFPJIDZHhAqlUPt281mHrBbZHqR
# K71Em3/hCGC5KyyneqiZ7syvFXJ9A72wzHpkBaMUNg7MOLxI6E9RaUueHTQKWXym
# OtRwJXcrcTTPPT2V1D/+cFllESviH8YjoPFvZSjKs3SKO1QNUdFd2adw44wDcKgH
# +JRJE5Qg0NP3yiSyi5MxgU6cehGHr7zou1znOM8odbkqoK+lJ25LCHBSai25CFyD
# 23DZgPfDrJJJK77epTwMP6eKA0kWa3osAe8fcpK40uhktzUd/Yk0xUvhDU6lvJuk
# x7jphx40DQt82yepyekl4i0r8OEps/FNO4ahfvAk12hE5FVs9HVVWcO5J4dVmVzi
# x4A77p3awLbr89A90/nWGjXMGn7FQhmSlIUDy9Z2hSgctaepZTd0ILIUbWuhKuAe
# NIeWrzHKYueMJtItnj2Q+aTyLLKLM0MheP/9w6CtjuuVHJOVoIJ/DtpJRE7Ce7vM
# RHoRon4CWIvuiNN1Lk9Y+xZ66lazs2kKFSTnnkrT3pXWETTJkhd76CIDBbTRofOs
# NyEhzZtCGmnQigpFHti58CSmvEyJcAlDVcKacJ+A9/z7eacCAwEAAaOCAZUwggGR
# MAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFOQ7/PIx7f391/ORcWMZUEPPYYzoMB8G
# A1UdIwQYMBaAFO9vU0rp5AZ8esrikFb2L9RJ7MtOMA4GA1UdDwEB/wQEAwIHgDAW
# BgNVHSUBAf8EDDAKBggrBgEFBQcDCDCBlQYIKwYBBQUHAQEEgYgwgYUwJAYIKwYB
# BQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBdBggrBgEFBQcwAoZRaHR0
# cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0VHJ1c3RlZEc0VGltZVN0
# YW1waW5nUlNBNDA5NlNIQTI1NjIwMjVDQTEuY3J0MF8GA1UdHwRYMFYwVKBSoFCG
# Tmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRydXN0ZWRHNFRpbWVT
# dGFtcGluZ1JTQTQwOTZTSEEyNTYyMDI1Q0ExLmNybDAgBgNVHSAEGTAXMAgGBmeB
# DAEEAjALBglghkgBhv1sBwEwDQYJKoZIhvcNAQELBQADggIBAGUqrfEcJwS5rmBB
# 7NEIRJ5jQHIh+OT2Ik/bNYulCrVvhREafBYF0RkP2AGr181o2YWPoSHz9iZEN/FP
# sLSTwVQWo2H62yGBvg7ouCODwrx6ULj6hYKqdT8wv2UV+Kbz/3ImZlJ7YXwBD9R0
# oU62PtgxOao872bOySCILdBghQ/ZLcdC8cbUUO75ZSpbh1oipOhcUT8lD8QAGB9l
# ctZTTOJM3pHfKBAEcxQFoHlt2s9sXoxFizTeHihsQyfFg5fxUFEp7W42fNBVN4ue
# LaceRf9Cq9ec1v5iQMWTFQa0xNqItH3CPFTG7aEQJmmrJTV3Qhtfparz+BW60OiM
# EgV5GWoBy4RVPRwqxv7Mk0Sy4QHs7v9y69NBqycz0BZwhB9WOfOu/CIJnzkQTwtS
# SpGGhLdjnQ4eBpjtP+XB3pQCtv4E5UCSDag6+iX8MmB10nfldPF9SVD7weCC3yXZ
# i/uuhqdwkgVxuiMFzGVFwYbQsiGnoa9F5AaAyBjFBtXVLcKtapnMG3VH3EmAp/js
# J3FVF3+d1SVDTmjFjLbNFZUWMXuZyvgLfgyPehwJVxwC+UpX2MSey2ueIu9THFVk
# T+um1vshETaWyQo8gmBto/m3acaP9QsuLj3FNwFlTxq25+T4QwX9xa6ILs84ZPvm
# povq90K8eWyG2N01c4IhSOxqt81nMIIGtDCCBJygAwIBAgIQDcesVwX/IZkuQEMi
# DDpJhjANBgkqhkiG9w0BAQsFADBiMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGln
# aUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMSEwHwYDVQQDExhE
# aWdpQ2VydCBUcnVzdGVkIFJvb3QgRzQwHhcNMjUwNTA3MDAwMDAwWhcNMzgwMTE0
# MjM1OTU5WjBpMQswCQYDVQQGEwJVUzEXMBUGA1UEChMORGlnaUNlcnQsIEluYy4x
# QTA/BgNVBAMTOERpZ2lDZXJ0IFRydXN0ZWQgRzQgVGltZVN0YW1waW5nIFJTQTQw
# OTYgU0hBMjU2IDIwMjUgQ0ExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
# AgEAtHgx0wqYQXK+PEbAHKx126NGaHS0URedTa2NDZS1mZaDLFTtQ2oRjzUXMmxC
# qvkbsDpz4aH+qbxeLho8I6jY3xL1IusLopuW2qftJYJaDNs1+JH7Z+QdSKWM06qc
# hUP+AbdJgMQB3h2DZ0Mal5kYp77jYMVQXSZH++0trj6Ao+xh/AS7sQRuQL37QXbD
# hAktVJMQbzIBHYJBYgzWIjk8eDrYhXDEpKk7RdoX0M980EpLtlrNyHw0Xm+nt5pn
# YJU3Gmq6bNMI1I7Gb5IBZK4ivbVCiZv7PNBYqHEpNVWC2ZQ8BbfnFRQVESYOszFI
# 2Wv82wnJRfN20VRS3hpLgIR4hjzL0hpoYGk81coWJ+KdPvMvaB0WkE/2qHxJ0ucS
# 638ZxqU14lDnki7CcoKCz6eum5A19WZQHkqUJfdkDjHkccpL6uoG8pbF0LJAQQZx
# st7VvwDDjAmSFTUms+wV/FbWBqi7fTJnjq3hj0XbQcd8hjj/q8d6ylgxCZSKi17y
# Vp2NL+cnT6Toy+rN+nM8M7LnLqCrO2JP3oW//1sfuZDKiDEb1AQ8es9Xr/u6bDTn
# YCTKIsDq1BtmXUqEG1NqzJKS4kOmxkYp2WyODi7vQTCBZtVFJfVZ3j7OgWmnhFr4
# yUozZtqgPrHRVHhGNKlYzyjlroPxul+bgIspzOwbtmsgY1MCAwEAAaOCAV0wggFZ
# MBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFO9vU0rp5AZ8esrikFb2L9RJ
# 7MtOMB8GA1UdIwQYMBaAFOzX44LScV1kTN8uZz/nupiuHA9PMA4GA1UdDwEB/wQE
# AwIBhjATBgNVHSUEDDAKBggrBgEFBQcDCDB3BggrBgEFBQcBAQRrMGkwJAYIKwYB
# BQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBBBggrBgEFBQcwAoY1aHR0
# cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0VHJ1c3RlZFJvb3RHNC5j
# cnQwQwYDVR0fBDwwOjA4oDagNIYyaHR0cDovL2NybDMuZGlnaWNlcnQuY29tL0Rp
# Z2lDZXJ0VHJ1c3RlZFJvb3RHNC5jcmwwIAYDVR0gBBkwFzAIBgZngQwBBAIwCwYJ
# YIZIAYb9bAcBMA0GCSqGSIb3DQEBCwUAA4ICAQAXzvsWgBz+Bz0RdnEwvb4LyLU0
# pn/N0IfFiBowf0/Dm1wGc/Do7oVMY2mhXZXjDNJQa8j00DNqhCT3t+s8G0iP5kvN
# 2n7Jd2E4/iEIUBO41P5F448rSYJ59Ib61eoalhnd6ywFLerycvZTAz40y8S4F3/a
# +Z1jEMK/DMm/axFSgoR8n6c3nuZB9BfBwAQYK9FHaoq2e26MHvVY9gCDA/JYsq7p
# GdogP8HRtrYfctSLANEBfHU16r3J05qX3kId+ZOczgj5kjatVB+NdADVZKON/gnZ
# ruMvNYY2o1f4MXRJDMdTSlOLh0HCn2cQLwQCqjFbqrXuvTPSegOOzr4EWj7PtspI
# HBldNE2K9i697cvaiIo2p61Ed2p8xMJb82Yosn0z4y25xUbI7GIN/TpVfHIqQ6Ku
# /qjTY6hc3hsXMrS+U0yy+GWqAXam4ToWd2UQ1KYT70kZjE4YtL8Pbzg0c1ugMZyZ
# Zd/BdHLiRu7hAWE6bTEm4XYRkA6Tl4KSFLFk43esaUeqGkH/wyW4N7OigizwJWeu
# kcyIPbAvjSabnf7+Pu0VrFgoiovRDiyx3zEdmcif/sYQsfch28bZeUz2rtY/9TCA
# 6TD8dC3JE3rYkrhLULy7Dc90G6e8BlqmyIjlgp2+VqsS9/wQD7yFylIz0scmbKvF
# oW2jNrbM1pD2T7m3XDCCBY0wggR1oAMCAQICEA6bGI750C3n79tQ4ghAGFowDQYJ
# KoZIhvcNAQEMBQAwZTELMAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IElu
# YzEZMBcGA1UECxMQd3d3LmRpZ2ljZXJ0LmNvbTEkMCIGA1UEAxMbRGlnaUNlcnQg
# QXNzdXJlZCBJRCBSb290IENBMB4XDTIyMDgwMTAwMDAwMFoXDTMxMTEwOTIzNTk1
# OVowYjELMAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UE
# CxMQd3d3LmRpZ2ljZXJ0LmNvbTEhMB8GA1UEAxMYRGlnaUNlcnQgVHJ1c3RlZCBS
# b290IEc0MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAv+aQc2jeu+Rd
# SjwwIjBpM+zCpyUuySE98orYWcLhKac9WKt2ms2uexuEDcQwH/MbpDgW61bGl20d
# q7J58soR0uRf1gU8Ug9SH8aeFaV+vp+pVxZZVXKvaJNwwrK6dZlqczKU0RBEEC7f
# gvMHhOZ0O21x4i0MG+4g1ckgHWMpLc7sXk7Ik/ghYZs06wXGXuxbGrzryc/NrDRA
# X7F6Zu53yEioZldXn1RYjgwrt0+nMNlW7sp7XeOtyU9e5TXnMcvak17cjo+A2raR
# mECQecN4x7axxLVqGDgDEI3Y1DekLgV9iPWCPhCRcKtVgkEy19sEcypukQF8IUzU
# vK4bA3VdeGbZOjFEmjNAvwjXWkmkwuapoGfdpCe8oU85tRFYF/ckXEaPZPfBaYh2
# mHY9WV1CdoeJl2l6SPDgohIbZpp0yt5LHucOY67m1O+SkjqePdwA5EUlibaaRBkr
# fsCUtNJhbesz2cXfSwQAzH0clcOP9yGyshG3u3/y1YxwLEFgqrFjGESVGnZifvaA
# sPvoZKYz0YkH4b235kOkGLimdwHhD5QMIR2yVCkliWzlDlJRR3S+Jqy2QXXeeqxf
# jT/JvNNBERJb5RBQ6zHFynIWIgnffEx1P2PsIV/EIFFrb7GrhotPwtZFX50g/KEe
# xcCPorF+CiaZ9eRpL5gdLfXZqbId5RsCAwEAAaOCATowggE2MA8GA1UdEwEB/wQF
# MAMBAf8wHQYDVR0OBBYEFOzX44LScV1kTN8uZz/nupiuHA9PMB8GA1UdIwQYMBaA
# FEXroq/0ksuCMS1Ri6enIZ3zbcgPMA4GA1UdDwEB/wQEAwIBhjB5BggrBgEFBQcB
# AQRtMGswJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBDBggr
# BgEFBQcwAoY3aHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0QXNz
# dXJlZElEUm9vdENBLmNydDBFBgNVHR8EPjA8MDqgOKA2hjRodHRwOi8vY3JsMy5k
# aWdpY2VydC5jb20vRGlnaUNlcnRBc3N1cmVkSURSb290Q0EuY3JsMBEGA1UdIAQK
# MAgwBgYEVR0gADANBgkqhkiG9w0BAQwFAAOCAQEAcKC/Q1xV5zhfoKN0Gz22Ftf3
# v1cHvZqsoYcs7IVeqRq7IviHGmlUIu2kiHdtvRoU9BNKei8ttzjv9P+Aufih9/Jy
# 3iS8UgPITtAq3votVs/59PesMHqai7Je1M/RQ0SbQyHrlnKhSLSZy51PpwYDE3cn
# RNTnf+hZqPC/Lwum6fI0POz3A8eHqNJMQBk1RmppVLC4oVaO7KTVPeix3P0c2PR3
# WlxUjG/voVA9/HYJaISfb8rbII01YBwCA8sgsKxYoA5AY8WYIsGyWfVVa88nq2x2
# zm8jLfR+cWojayL/ErhULSd+2DrZ8LaHlv1b0VysGMNNn3O3AamfV6peKOK5lDGC
# A3wwggN4AgEBMH0waTELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDkRpZ2lDZXJ0LCBJ
# bmMuMUEwPwYDVQQDEzhEaWdpQ2VydCBUcnVzdGVkIEc0IFRpbWVTdGFtcGluZyBS
# U0E0MDk2IFNIQTI1NiAyMDI1IENBMQIQCoDvGEuN8QWC0cR2p5V0aDANBglghkgB
# ZQMEAgEFAKCB0TAaBgkqhkiG9w0BCQMxDQYLKoZIhvcNAQkQAQQwHAYJKoZIhvcN
# AQkFMQ8XDTI2MDcwMjEzMTg0N1owKwYLKoZIhvcNAQkQAgwxHDAaMBgwFgQU3WIw
# rIYKLTBr2jixaHlSMAf7QX4wLwYJKoZIhvcNAQkEMSIEIF9kwWucarTyy1lsh0nh
# xUgjRN5XFaLPiPsbpWIXJvz8MDcGCyqGSIb3DQEJEAIvMSgwJjAkMCIEIEqgP6Is
# 11yExVyTj4KOZ2ucrsqzP+NtJpqjNPFGEQozMA0GCSqGSIb3DQEBAQUABIICAIAA
# zOiimvtA/2lLBzx3zrjhZS49pSx3neAdWP1zKKoybRjRMbxtb+rp+rWskuXfrlN8
# yo0sEQxR6UGNhAcc+mTdBVk0cr5epV0EUTJEwHccoT9EUANPdoxoUbhsvMtKwpbJ
# VYOgr86Sk/fSU8ujSrif/aCAEMEMZ9CcO3W+Pp/nsvfjCDhhbeU9eK68iFNzBEN5
# OpwACar4e1dJxMSvXeQc22WUu/VQ1IV6D+lNaO5OyuLzIJFvZ0SYC0a0uA8vRAov
# LG2e/ThtAqa9wqDFFyrsNbnbhgpkITDCC+J8pc1rccsWILeJm8kONyNw0abwdZ0L
# I5m3ohvq6JeHffkDrDAlNYVCQg/yFgEr4rx7K1SH0hlNvORFJq9Qcr+MTZhIjFCC
# 1JgSZ9OpHhe/GpaxQGB6bHxBOU8SE4LJL5EuSelwvog/3J7pPBBPOHywVLXoxLyh
# BD3ac6wNS/pydTAnU+HOhOE9fXH9Cc7e7Gh1iGYBmh1rjLD9yWMJBPh3jPlhf/Tu
# asNu28l+JXX2ja0e8OA4v8Rzqw/klXwrG7U2W/rDFooCFzI3ppsgX51vQfP8gX7O
# J+aCYZmOEkmNuD2HuDqXbI4vtGqIXgXMru8FhjV1d/jU/XZxfxyVCtXCNgBNBGwu
# Bh4dm9yhL+FNGPXoHTrdV/Ti1fwkiNL34SGhIZLT
# SIG # End signature block
